services:
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - .:/app
    working_dir: /app
    env_file: .env
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
