services:
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - .:/app
    working_dir: /app
    env_file: .env
    depends_on:
      - mysql
      - postgres
      - mssql
      - oracle
      - firebird

  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'

  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: '${DB_PASSWORD}'

  oracle:
    image: gvenzl/oracle-xe
    environment:
      ORACLE_RANDOM_PASSWORD: true
      APP_USER: '${DB_USERNAME}'
      APP_USER_PASSWORD: '${DB_PASSWORD}'

  firebird:
    image: jacobalberty/firebird
    environment:
      FIREBIRD_DATABASE: '${DB_DATABASE}'
      FIREBIRD_USER: '${DB_USERNAME}'
      FIREBIRD_PASSWORD: '${DB_PASSWORD}'
